name: CI

on:
  push:
    branches:
      - stock

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker image for testing
        run: docker build . -t robot-framework-tests

      - name: Run Robot Framework tests
        run: docker run robot-framework-tests

      - name: Check Test Results
        run: |
          if grep -q "FAIL" output.xml; then
            echo "Some tests failed."
            exit 1
          else
            echo "All tests passed."

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'

      - name: Build Go project
        run: go build -v ./...

      - name: Test Go project
        run: go test -v ./...
